# GitHub Pages configuration
# No theme needed for custom HTML
title: On the Generalisation of Koopman Representations for Chaotic System Control
description: Evaluating Koopman representation generalizability for transformer-based chaos prediction and control
